# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f795fff143badff28cb5905adafeaf2434a3a3f519e1665f0728aae1f55ac1c95845a348d70835d0bb30c7030aab5ced2dcd780be97af53e22eb071bdca2fe

test:
  secret_key_base: f1452d38953e5ca48f629cb985fce7bde39d6645b3fb05289ae3880679a3cab4327cf8fa16ff534436f68ede34d2c284fdf0498ff2720d48b85a4ec5087bb6f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
